baseURL: https://reseau-protestant.ch/
languageCode: fr-ch
defaultContentLanguage: fr
title: Réseau protestant

params:
  description: Sites protestants réformés de Suisse romande en réseau.
  images: 
    - /img/network.jpg


disableKinds:
  - taxonomy
  - taxonomyTerm